apiVersion: v1
kind: Service
metadata:
  name: trading-app-dev
  labels:
    app: trading-app
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: trading-app
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: trading-app-dev
  labels:
    app: trading-app
spec:
  selector:
    matchLabels:
      app: trading-app
      tier: frontend
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: trading-app
        tier: frontend
    spec:
      containers:
      - image: onehoax.azurecr.io/trading-app:latest
        name: trading-app
        env:
        - name: PSQL_URL
          value: jdbc:postgresql://trading-psql-dev:5432/jrvstrading 
        - name: PSQL_USER
          value: postgres
        - name: PSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-pass
              key: password
        - name: token
          valueFrom:
            secretKeyRef:
              name: iex-token
              key: token
        ports:
        - containerPort: 5000
          name: trading-app
