apiVersion: v1
kind: Service
metadata:
  name: trading-psql
  labels:
    app: trading-app
spec:
  ports:
    - port: 5432
  selector:
    app: trading-app
    tier: psql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pv-claim
  labels:
    app: trading-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: trading-psql
  labels:
    app: trading-app
spec:
  selector:
    matchLabels:
      app: trading-app
      tier: psql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: trading-app
        tier: psql
    spec:
      containers:
      - image: onehoax.azurecr.io/trading-psql:latest
        name: trading-psql
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: psql-pass
              key: password
        ports:
        - containerPort: 5432
          name: trading-psql
        volumeMounts:
        - name: psql-persistent-storage
          mountPath: /var/lib/psql
      volumes:
      - name: psql-persistent-storage
        persistentVolumeClaim:
          claimName: psql-pv-claim
